apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Provider
metadata:
  name: provider-jet-opsgenie-provider
spec:
  controller:
    image: DOCKER_REGISTRY/provider-jet-opsgenie-provider-controller:VERSION